project_id           = "celonis-labs"
pool_id              = "example"
provider_id          = "example-infra"
issuer_uri           = "https://token.actions.githubusercontent.com"
service_account_name = "example-infra@celonis-labs.iam.gserviceaccount.com"
github_repository    = "sergibarroso/example-infra"
