controller:
  resources:
    limits:
      cpu: 200m
      memory: 200Mi
    requests:
      cpu: 100m
      memory: 90Mi
  containerSecurityContext:
    runAsNonRoot: true
    allowPrivilegeEscalation: false
    runAsUser: 101
  service:
    external:
      enabled: true
    internal:
      enabled: false
      # annotations:
      #   # Create internal LB. More information: https://cloud.google.com/kubernetes-engine/docs/how-to/internal-load-balancing
      #   # For GKE versions 1.17 and later
      #   networking.gke.io/load-balancer-type: 'Internal'
