installCRDs: true
image:
  registry: quay.io
  repository: jetstack/cert-manager-controller
prometheus:
  enabled: false
resources:
  requests:
    cpu: 50m
    memory: 200Mi
  limits:
    cpu: 50m
    memory: 200Mi
securityContext:
  fsGroup: 1001
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault
serviceAccount:
  create: true
  name: cert-manager
  # annotations:
  #   iam.gke.io/gcp-service-account:
containerSecurityContext:
  runAsNonRoot: true
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
  runAsUser: 1001
  runAsGroup: 1001
  capabilities:
    drop:
      - ALL
  seccompProfile:
    type: RuntimeDefault

webhook:
  securityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  containerSecurityContext:
    runAsNonRoot: true
    readOnlyRootFilesystem: true
    allowPrivilegeEscalation: false
    runAsUser: 1001
    runAsGroup: 1001
    capabilities:
      drop:
        - ALL
    seccompProfile:
      type: RuntimeDefault
  image:
    registry: quay.io
    repository: jetstack/cert-manager-webhook
  resources:
    requests:
      cpu: 50m
      memory: 200Mi
    limits:
      cpu: 50m
      memory: 200Mi

cainjector:
  securityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  containerSecurityContext:
    runAsNonRoot: true
    readOnlyRootFilesystem: true
    allowPrivilegeEscalation: false
    runAsUser: 1001
    runAsGroup: 1001
    capabilities:
      drop:
        - ALL
    seccompProfile:
      type: RuntimeDefault
  image:
    registry: quay.io
    repository: jetstack/cert-manager-cainjector
  resources:
    requests:
      cpu: 50m
      memory: 400Mi
    limits:
      cpu: 50m
      memory: 400Mi

startupapicheck:
  resources:
    requests:
      cpu: 50m
      memory: 200Mi
    limits:
      cpu: 50m
      memory: 200Mi
  containerSecurityContext:
    runAsNonRoot: true
    readOnlyRootFilesystem: true
    allowPrivilegeEscalation: false
    runAsUser: 1001
    runAsGroup: 1001
    capabilities:
      drop:
        - ALL
    seccompProfile:
      type: RuntimeDefault
  securityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
