---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: example-issuer
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: sergibarroso@gmail.com
    privateKeySecretRef:
      name: letsencrypt
    solvers:
      - dns01:
          cloudDNS:
            project: celonis-labs
            

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: example-cert
  namespace: cert-manager
spec:
  secretName: example-cert-tls
  issuerRef:
    name: example-issuer
  dnsNames:
    - '*.example-app.example-team.sbt-challenge.org'
