---
apiVersion: v1
kind: Namespace
metadata:
  name: example-app

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tenant-sa
  namespace: example-app
  annotations:
    iam.gke.io/gcp-service-account: example-app@celonis-labs.iam.gserviceaccount.com

---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: namespace-quota
  namespace: example-app
spec:
  hard:
    services.loadbalancers: 0

---
apiVersion: v1
kind: LimitRange
metadata:
  name: namespace-limits
  namespace: example-app
spec:
  limits:
    - type: Container
      default:
        cpu: 2000m
        memory: 1Gi
      defaultRequest:
        cpu: '2'
        memory: 1Gi

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tenant-role
  namespace: example-app
rules:
  - apiGroups: ['']
    resources: ['events']
    verbs: ['create', 'get', 'watch', 'list']
  - apiGroups: ['']
    resources: ['secrets']
    verbs: ['*']
  - apiGroups: ['']
    resources:
      - pods
      - pods/log
      - configmaps
      - persistentvolumeclaims
      - serviceaccounts
      - services
    verbs: ['*']
  - apiGroups: ['apps']
    resources: ['deployments', 'replicasets', 'statefulsets']
    verbs: ['*']
  - apiGroups: ['autoscaling']
    resources: ['horizontalpodautoscalers']
    verbs: ['*']
  - apiGroups: ['batch']
    resources: ['cronjobs', 'jobs']
    verbs: ['*']
  - apiGroups: ['networking.k8s.io']
    resources: ['ingresses', 'networkpolicies', 'ingresses/status']
    verbs: ['*']
  - apiGroups: ['policy']
    resources: ['poddisruptionbudgets']
    verbs: ['*']
  - apiGroups: ['rbac.authorization.k8s.io']
    resources: ['roles', 'rolebindings']
    verbs: ['*']

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tenant-role
  namespace: example-app
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tenant-role
subjects:
  - kind: ServiceAccount
    name: tenant-sa
    namespace: example-app
  - kind: Group
    name: 'tenant:example-app'
    apiGroup: rbac.authorization.k8s.io
